### ISSUE TITLE
Planning issue .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-blurred-location-display#17]
###  Task List  ⭐️  : 

- [ ] 1. A spec for describing the precision of location data in human terms
    - this wouldn't need to be incredibly formal, but we would basically try to write out a very precise and clear description of the role LBL fulfills, abstractly. It could include very clear examples of how location is blurred and how much precision it "degrades" for each level. Does this make sense?

- [ ] 2. A utility library for filtering locations to a specific precision level
    - this would be a mini sub-node module broken out of LBL that could be re-used in LBLD, and also in other apps, that would just do the conversions - no UI or geocoding or anything! This should be pretty easy and could have a set of tests to demonstrate how it works (that could overlap a lot with the spec task above)

**Comment by sagarpreet-chadha** [comment]
@jywarren ...lets add here 😄 !

**Comment by jywarren** [comment]
Looking great!

* [ ] Let's write tests that assert the markers are shown or hidden as in the new example code!
* [ ] let's separate out the UI code like popup code from the data management code using require()
* [ ] let's clarify what happens when local static data AND remote url are both provided, or move to do only one or the other per layer
* [ ] Let's make a demo of switching between shading and markers modes using a toggle (later when we're ready!)

How do these sound?

**Comment by jywarren** [comment]
Let's also 

* [ ] standardize the method names returned by the constructor function to be more readable and clear
* [ ] make some functions like getMarkersOfPrecision(int) and filterCoordinatesToPrecison(int)

**Comment by jywarren** [comment]
Hi @sagarpreet-chadha could you update these checkboxes so I can get synced up about progress? Thank you so much!!!

**Comment by sagarpreet-chadha** [comment]
@jywarren ...done 👍 !

**Comment by jywarren** [comment]
OK, we're almost there -- can you check off items again? thank you!!!

**Comment by sagarpreet-chadha** [comment]
Done :+1:  !
